#include <bits/stdc++.h>
using namespace std;using ll=long long;
static int snap(long double v){return (int)llroundl(v);} 
static bool solve_axis(const int P[3],const int F[3],int order,ll &k,ll &c,bool &unique){if(P[0]==P[1]&&P[0]==P[2]){if(!(F[0]==F[1]&&F[0]==F[2]))return false;unique=false;return true;}int i=0,j=1;if(P[i]==P[j])j=2;if(P[i]==P[j]){i=1;j=2;}ll denom=(ll)P[i]-P[j];ll numer=(ll)F[i]-F[j];if(numer%denom)return false;k=numer/denom;if(k==0)return false;c=(ll)F[i]-k*P[i];if(order==1&&c%k)return false;for(int t=0;t<3;++t)if((ll)F[t]!=k*P[t]+c)return false;unique=true;return true;}
struct Map{int rot;ll kx,ky,cx,cy;int order;vector<int> perm;bool operator==(const Map&o)const{return rot==o.rot&&kx==o.kx&&ky==o.ky&&cx==o.cx&&cy==o.cy;}};
int main(){int X0[3]={3,4,1},Y0[3]={0,0,4},XF[3]={-2,-1,3},YF[3]={-4,3,-4};vector<pair<int,int>> dirs;for(int x=-10;x<=10;++x)for(int y=-10;y<=10;++y)if((x||y)&&(abs(x)==10||abs(y)==10))dirs.emplace_back(x,y);
vector<Map> maps;vector<int> perm={0,1,2};for(int rotId=0;rotId<(int)dirs.size();++rotId){auto[rx,ry]=dirs[rotId];long double len=hypotl((long double)rx,(long double)ry);long double cs=rx/len,sn=ry/len;int PRx[3],PRy[3];for(int i=0;i<3;++i){ long double xr=(long double)X0[i]*cs-(long double)Y0[i]*sn; long double yr=(long double)X0[i]*sn+(long double)Y0[i]*cs; PRx[i]=snap(xr); PRy[i]=snap(yr);} sort(perm.begin(),perm.end()); do{int FX[3],FY[3];for(int i=0;i<3;++i){FX[i]=XF[perm[i]];FY[i]=YF[perm[i]];} for(int order=0;order<2;++order){ll kx=0,ky=0,cx=0,cy=0;bool ux=false,uy=false;if(!solve_axis(PRx,FX,order,kx,cx,ux))continue;if(!solve_axis(PRy,FY,order,ky,cy,uy))continue;if(!ux||!uy)continue;Map m{rotId,kx,ky,cx,cy,order,perm}; bool dup=false; for(auto &mm:maps) if(m==mm) {dup=true; break;} if(!dup) maps.push_back(m);} }while(next_permutation(perm.begin(),perm.end()));}
cout<<"maps size="<<maps.size()<<"\n";for(auto &m:maps){cout<<"rot="<<m.rot<<" kx="<<m.kx<<" cx="<<m.cx<<" ky="<<m.ky<<" cy="<<m.cy<<" order="<<m.order<<" perm="<<m.perm[0]<<m.perm[1]<<m.perm[2]<<"\n";} 
for(int pt=0;pt<5;++pt){int X=pt,Y=pt-2;long double len1=hypotl((long double)dirs[maps[0].rot].first,(long double)dirs[maps[0].rot].second);long double cs1=dirs[maps[0].rot].first/len1;long double sn1=dirs[maps[0].rot].second/len1;long double xr1=X*cs1 - Y*sn1; long double yr1=X*sn1 + Y*cs1; int prx1=snap(xr1); int pry1=snap(yr1); long long resx1=maps[0].kx*prx1+maps[0].cx; long long resy1=maps[0].ky*pry1+maps[0].cy;
long double len2=hypotl((long double)dirs[maps[1].rot].first,(long double)dirs[maps[1].rot].second);long double cs2=dirs[maps[1].rot].first/len2;long double sn2=dirs[maps[1].rot].second/len2; long double xr2=X*cs2 - Y*sn2; long double yr2=X*sn2 + Y*cs2; int prx2=snap(xr2); int pry2=snap(yr2); long long resx2=maps[1].kx*prx2+maps[1].cx; long long resy2=maps[1].ky*pry2+maps[1].cy; cout<<"Pt("<<X<<","<<Y<<") -> M1("<<resx1<<","<<resy1<<") M2("<<resx2<<","<<resy2<<")\n";}